// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvlkgcgsldbggsuouty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdmxrZ2Nnc2xkYmdnc3VvdXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTc0MzUsImV4cCI6MjA2NDg5MzQzNX0.fhPjkyttV8Mz0z2_wQpcHR5ViRlPAOGnJN1TAPnNbDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);